global:
  scrape_interval: 4s

scrape_configs:
  - job_name: 'nodejs-app'
    static_configs:
      - targets: ['192.168.0.110:3000']  # Node.js application endpoint

  - job_name: 'mongodb'
    static_configs:
      - targets: ['192.168.0.110:9216']  # MongoDB Exporter endpoint
